;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        backward-sexp
        delete-horizontal-space
        ess-smart-comma
        ess-yank
        go-mode-insert-and-indent
        iy-go-to-char--command
        kill-sexp
        search-forward
        yas-expand
        z-exchange-point-and-mark
        z-toggle-activate-mark
        z-zap-up-to-char
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        god-mode-all
        smex
        ))
