;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        delete-horizontal-space
        ess-smart-comma
        ess-yank
        go-mode-insert-and-indent
        kill-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
