; -*- coding: utf-8; lexical-binding: t -*-

(let ((quail-current-package (assoc "TeX" quail-package-alist)))
  (quail-define-rules
   ((append . t))
   ("^\\alpha" ?ᵅ) ("\\sqrt" ?√)

   ("\\mathbb{A}" ?𝔸) ("\\mathbb{B}" ?𝔹)
   ("\\mathbb{C}" ?ℂ) ("\\mathbb{D}" ?𝔻)
   ("\\mathbb{E}" ?𝔼) ("\\mathbb{F}" ?𝔽)
   ("\\mathbb{G}" ?𝔾) ("\\mathbb{H}" ?ℍ)
   ("\\mathbb{I}" ?𝕀) ("\\mathbb{J}" ?𝕁)
   ("\\mathbb{K}" ?𝕂) ("\\mathbb{L}" ?𝕃)
   ("\\mathbb{M}" ?𝕄) ("\\mathbb{N}" ?ℕ)
   ("\\mathbb{O}" ?𝕆) ("\\mathbb{P}" ?ℙ)
   ("\\mathbb{Q}" ?ℚ) ("\\mathbb{R}" ?ℝ)
   ("\\mathbb{S}" ?𝕊) ("\\mathbb{T}" ?𝕋)
   ("\\mathbb{U}" ?𝕌) ("\\mathbb{V}" ?𝕍)
   ("\\mathbb{W}" ?𝕎) ("\\mathbb{X}" ?𝕏)
   ("\\mathbb{Y}" ?𝕐) ("\\mathbb{Z}" ?ℤ)

   ("\\mathbb{a}" ?𝕒) ("\\mathbb{b}" ?𝕓)
   ("\\mathbb{c}" ?𝕔) ("\\mathbb{d}" ?𝕕)
   ("\\mathbb{e}" ?𝕖) ("\\mathbb{f}" ?𝕗)
   ("\\mathbb{g}" ?𝕘) ("\\mathbb{h}" ?𝕙)
   ("\\mathbb{i}" ?𝕚) ("\\mathbb{j}" ?𝕛)
   ("\\mathbb{k}" ?𝕜) ("\\mathbb{l}" ?𝕝)
   ("\\mathbb{m}" ?𝕞) ("\\mathbb{n}" ?𝕟)
   ("\\mathbb{o}" ?𝕠) ("\\mathbb{p}" ?𝕡)
   ("\\mathbb{q}" ?𝕢) ("\\mathbb{r}" ?𝕣)
   ("\\mathbb{s}" ?𝕤) ("\\mathbb{t}" ?𝕥)
   ("\\mathbb{u}" ?𝕦) ("\\mathbb{v}" ?𝕧)
   ("\\mathbb{w}" ?𝕨) ("\\mathbb{x}" ?𝕩)
   ("\\mathbb{y}" ?𝕪) ("\\mathbb{z}" ?𝕫)

   ("\\mathbb{0}" ?𝟘) ("\\mathbb{1}" ?𝟙)
   ("\\mathbb{2}" ?𝟚) ("\\mathbb{3}" ?𝟛)
   ("\\mathbb{4}" ?𝟜) ("\\mathbb{5}" ?𝟝)
   ("\\mathbb{6}" ?𝟞) ("\\mathbb{7}" ?𝟟)
   ("\\mathbb{8}" ?𝟠) ("\\mathbb{9}" ?𝟡)

   ;; some of these are more like mathcal, but since we already have
   ;; \mathscr{I}, roll with that.
   ("\\mathscr{A}" ?𝒜) ("\\mathscr{B}" ?ℬ)
   ("\\mathscr{C}" ?𝒞) ("\\mathscr{D}" ?𝒟)
   ("\\mathscr{E}" ?ℰ) ("\\mathscr{F}" ?ℱ)
   ("\\mathscr{G}" ?𝒢) ("\\mathscr{H}" ?ℋ)
   ;;("\\mathscr{I}" ?ℐ) ; already there
   ("\\mathscr{J}" ?𝒥)
   ("\\mathscr{K}" ?𝒦) ("\\mathscr{L}" ?ℒ)
   ("\\mathscr{M}" ?ℳ) ("\\mathscr{N}" ?𝒩)
   ("\\mathscr{O}" ?𝒪) ("\\mathscr{P}" ?𝒫)
   ("\\mathscr{Q}" ?𝒬) ("\\mathscr{R}" ?ℛ)
   ("\\mathscr{S}" ?𝒮) ("\\mathscr{T}" ?𝒯)
   ("\\mathscr{U}" ?𝒰) ("\\mathscr{V}" ?𝒱)
   ("\\mathscr{W}" ?𝒲) ("\\mathscr{X}" ?𝒳)
   ("\\mathscr{Y}" ?𝒴) ("\\mathscr{Z}" ?𝒵)

   ("\\mathscr{a}" ?𝒶)("\\mathscr{b}" ?𝒷)
   ("\\mathscr{c}" ?𝒸)("\\mathscr{d}" ?𝒹)
   ("\\mathscr{e}" ?ℯ)("\\mathscr{f}" ?𝒻)
   ("\\mathscr{g}" ?ℊ)("\\mathscr{h}" ?𝒽)
   ("\\mathscr{i}" ?𝒾)("\\mathscr{j}" ?𝒿)
   ("\\mathscr{k}" ?𝓀)("\\mathscr{l}" ?𝓁)
   ("\\mathscr{m}" ?𝓂)("\\mathscr{n}" ?𝓃)
   ("\\mathscr{o}" ?ℴ)("\\mathscr{p}" ?𝓅)
   ("\\mathscr{q}" ?𝓆)("\\mathscr{r}" ?𝓇)
   ("\\mathscr{s}" ?𝓈)("\\mathscr{t}" ?𝓉)
   ("\\mathscr{u}" ?𝓊)("\\mathscr{v}" ?𝓋)
   ("\\mathscr{w}" ?𝓌)("\\mathscr{x}" ?𝓍)
   ("\\mathscr{y}" ?𝓎)("\\mathscr{z}" ?𝓏)

   ("\\mathfrak{A}" ?𝔄) ("\\mathfrak{B}" ?𝔅)
   ("\\mathfrak{C}" ?ℭ) ("\\mathfrak{D}" ?𝔇)
   ("\\mathfrak{E}" ?𝔈) ("\\mathfrak{F}" ?𝔉)
   ("\\mathfrak{G}" ?𝔊) ("\\mathfrak{H}" ?ℌ)
   ("\\mathfrak{I}" ?ℑ) ("\\mathfrak{J}" ?𝔍)
   ("\\mathfrak{K}" ?𝔎) ("\\mathfrak{L}" ?𝔏)
   ("\\mathfrak{M}" ?𝔐) ("\\mathfrak{N}" ?𝔑)
   ("\\mathfrak{O}" ?𝔒) ("\\mathfrak{P}" ?𝔓)
   ("\\mathfrak{Q}" ?𝔔) ("\\mathfrak{R}" ?ℜ)
   ("\\mathfrak{S}" ?𝔖) ("\\mathfrak{T}" ?𝔗)
   ("\\mathfrak{U}" ?𝔘) ("\\mathfrak{V}" ?𝔙)
   ("\\mathfrak{W}" ?𝔚) ("\\mathfrak{X}" ?𝔛)
   ("\\mathfrak{Y}" ?𝔜) ("\\mathfrak{Z}" ?ℨ)

   ("\\mathfrak{a}" ?𝔞) ("\\mathfrak{b}" ?𝔟)
   ("\\mathfrak{c}" ?𝔠) ("\\mathfrak{d}" ?𝔡)
   ("\\mathfrak{e}" ?𝔢) ("\\mathfrak{f}" ?𝔣)
   ("\\mathfrak{g}" ?𝔤) ("\\mathfrak{h}" ?𝔥)
   ("\\mathfrak{i}" ?𝔦) ("\\mathfrak{j}" ?𝔧)
   ("\\mathfrak{k}" ?𝔨) ("\\mathfrak{l}" ?𝔩)
   ("\\mathfrak{m}" ?𝔪) ("\\mathfrak{n}" ?𝔫)
   ("\\mathfrak{o}" ?𝔬) ("\\mathfrak{p}" ?𝔭)
   ("\\mathfrak{q}" ?𝔮) ("\\mathfrak{r}" ?𝔯)
   ("\\mathfrak{s}" ?𝔰) ("\\mathfrak{t}" ?𝔱)
   ("\\mathfrak{u}" ?𝔲) ("\\mathfrak{v}" ?𝔳)
   ("\\mathfrak{w}" ?𝔴) ("\\mathfrak{x}" ?𝔵)
   ("\\mathfrak{y}" ?𝔶) ("\\mathfrak{z}" ?𝔷)

   ("\\rarr" ?→) ("\\larr" ?←) ("\\uarr" ?↑) ("\\darr" ?↓)
   ("\\Rarr" ?⇒) ("\\Larr" ?⇐) ("\\Uarr" ?⇑) ("\\Darr" ?⇓)))
