; -*- coding: utf-8; lexical-binding: t -*-

(let ((quail-current-package (assoc "TeX" quail-package-alist)))
  (quail-define-rules
   ((append . t))
   ("^\\alpha" ?ᵅ) ("\\sqrt" ?√)
   ("\\mathbb{A}" ?𝔸) ("\\mathbb{B}" ?𝔹)
   ("\\mathbb{C}" ?ℂ) ("\\mathbb{D}" ?𝔻)
   ("\\mathbb{E}" ?𝔼) ("\\mathbb{F}" ?𝔽)
   ("\\mathbb{G}" ?𝔾) ("\\mathbb{H}" ?ℍ)
   ("\\mathbb{I}" ?𝕀) ("\\mathbb{J}" ?𝕁)
   ("\\mathbb{K}" ?𝕂) ("\\mathbb{L}" ?𝕃)
   ("\\mathbb{M}" ?𝕄) ("\\mathbb{N}" ?ℕ)
   ("\\mathbb{O}" ?𝕆) ("\\mathbb{P}" ?ℙ)
   ("\\mathbb{Q}" ?ℚ) ("\\mathbb{R}" ?ℝ)
   ("\\mathbb{S}" ?𝕊) ("\\mathbb{T}" ?𝕋)
   ("\\mathbb{U}" ?𝕌) ("\\mathbb{V}" ?𝕍)
   ("\\mathbb{W}" ?𝕎) ("\\mathbb{X}" ?𝕏)
   ("\\mathbb{Y}" ?𝕐) ("\\mathbb{Z}" ?ℤ)
   ("\\mathbb{0}" ?𝟘) ("\\mathbb{1}" ?𝟙)
   ("\\mathbb{2}" ?𝟚) ("\\mathbb{3}" ?𝟛)
   ("\\mathbb{4}" ?𝟜) ("\\mathbb{5}" ?𝟝)
   ("\\mathbb{6}" ?𝟞) ("\\mathbb{7}" ?𝟟)
   ("\\mathbb{8}" ?𝟠) ("\\mathbb{9}" ?𝟡)
   ("\\mathscr{A}" ?𝒜) ("\\mathscr{B}" ?ℬ)
   ("\\mathscr{C}" ?𝒞) ("\\mathscr{D}" ?𝒟)
   ("\\mathscr{E}" ?ℰ) ("\\mathscr{F}" ?ℱ)
   ("\\mathscr{G}" ?𝒢) ("\\mathscr{H}" ?ℋ)
   ;;("\\mathscr{I}" ?ℐ) ; already there
   ("\\mathscr{J}" ?𝒥)
   ("\\mathscr{K}" ?𝒦) ("\\mathscr{L}" ?ℒ)
   ("\\mathscr{M}" ?ℳ) ("\\mathscr{N}" ?𝒩)
   ("\\mathscr{O}" ?𝒪) ("\\mathscr{P}" ?𝒫)
   ("\\mathscr{Q}" ?𝒬) ("\\mathscr{R}" ?ℛ)
   ("\\mathscr{S}" ?𝒮) ("\\mathscr{T}" ?𝒯)
   ("\\mathscr{U}" ?𝒰) ("\\mathscr{V}" ?𝒱)
   ("\\mathscr{W}" ?𝒲) ("\\mathscr{X}" ?𝒳)
   ("\\mathscr{Y}" ?𝒴) ("\\mathscr{Z}" ?𝒵)
   ("\\rarr" ?→) ("\\larr" ?←) ("\\uarr" ?↑) ("\\darr" ?↓)
   ("\\Rarr" ?⇒) ("\\Larr" ?⇐) ("\\Uarr" ?⇑) ("\\Darr" ?⇓)))
